import type { CocodStatus } from '../runtime.js';
import { V1HttpError } from './contract.js';

/** Runtime validator paired with the JSON Schema emitted for the same document. */
export interface RuntimeSchema<T> {
  readonly name: string;
  readonly jsonSchema: Readonly<Record<string, unknown>>;
  parse(value: unknown): T;
}

/** Stable error codes that v1 clients may branch on. */
export const V1_ERROR_CODES = [
  'unauthenticated',
  'forbidden',
  'invalid_request',
  'not_found',
  'method_not_allowed',
  'unsupported_behavior',
  'invalid_operation_state',
  'operation_result_not_available',
  'internal_error',
  'invalid_idempotency_key',
  'idempotency_key_conflict',
  'idempotency_capacity_exceeded',
  'wallet_already_configured',
  'wallet_not_configured',
  'passphrase_required',
  'wallet_unlock_failed',
  'session_transition_in_progress',
  'session_restart_required',
  'wallet_locked',
  'session_stopped',
  'coco_error',
  'process_shutting_down',
] as const;

/** Stable machine-readable code carried by every v1 error document. */
export type V1ErrorCode = (typeof V1_ERROR_CODES)[number];

/** Common v1 error response returned without a legacy envelope. */
export interface V1ErrorDocument {
  error: {
    code: V1ErrorCode;
    message: string;
    retryable: boolean;
    details?: Record<string, unknown>;
  };
}

/** Public process-liveness document that contains no Wallet state. */
export interface HealthDocument {
  status: 'ok';
  interfaceVersion: '1';
}

/** Authenticated Wallet, Seed Access, and Coco Session status document. */
export interface LifecycleStatusDocument {
  daemon: {
    version: string;
    interfaceVersion: '1';
  };
  wallet: {
    configuredAt: string;
  } | null;
  seedAccess: CocodStatus['seedAccess'];
  cocoSession: CocodStatus['cocoSession'];
}

/** Network Wallet initialization input; recovery material is always generated by cocod. */
export interface InitializeWalletRequest {
  passphrase?: string;
}

/** Wallet Recovery Material retrieval input containing optional Wallet-unlocking material. */
export interface WalletRecoveryMaterialRequest {
  passphrase?: string;
}

/** Coco Session start input containing optional Wallet-unlocking material. */
export interface StartSessionRequest {
  passphrase?: string;
}

/** Coco Session stop accepts an empty JSON object. */
export type StopSessionRequest = Record<string, never>;

/** Cocod Process shutdown accepts an empty JSON object. */
export type ProcessShutdownRequest = Record<string, never>;

/** Non-cacheable result returned after cocod durably configures its generated Wallet. */
export interface InitializeWalletResponseDocument {
  generatedMnemonic: string;
  status: LifecycleStatusDocument;
}

/** Sensitive Wallet Recovery Material returned only by the administrative retrieval route. */
export interface WalletRecoveryMaterialResponseDocument {
  mnemonic: string;
}

/** Acknowledges that Cocod Process shutdown has been accepted. */
export interface ProcessShutdownResponseDocument {
  status: 'stopping';
}

/** Safe balance projection for one Known Mint and unit. */
export interface BalanceDocument {
  mintUrl: string;
  unit: string;
  spendable: string;
  reserved: string;
  total: string;
}

/** Flat collection of Wallet balances without cross-unit aggregation. */
export interface BalancesDocument {
  items: BalanceDocument[];
}

/** Body used by Known Mint registration and trust commands. */
export interface MintUrlRequest {
  mintUrl: string;
}

/** Safe cocod projection of Coco's Known Mint model. */
export interface KnownMintDocument {
  mintUrl: string;
  name: string;
  trusted: boolean;
  createdAt: string;
  updatedAt: string;
}

/** Collection of Known Mints. */
export interface KnownMintsDocument {
  items: KnownMintDocument[];
}

/** Mint metadata resolved through Coco and scoped to its normalized identity. */
export interface MintInformationDocument {
  mintUrl: string;
  info: Record<string, unknown>;
}

/** Safe projection of one Coco Payment Method Capability. */
export interface PaymentMethodCapabilityDocument {
  operation: 'mint' | 'melt';
  nut: 4 | 5;
  method: string;
  unit: string;
  minAmount?: string | null;
  maxAmount?: string | null;
  options?: unknown;
}

/** Collection of capabilities advertised by one Known Mint. */
export interface PaymentMethodCapabilitiesDocument {
  items: PaymentMethodCapabilityDocument[];
}

/** Method-specific Mint Quote creation input with lossless decimal amounts. */
export type CreateMintQuoteRequest =
  | {
      mintUrl: string;
      method: 'bolt11';
      amount: string;
      unit: string;
      locked?: boolean;
    }
  | { mintUrl: string; method: 'onchain'; unit: string }
  | {
      mintUrl: string;
      method: 'bolt12';
      unit: string;
      amount?: string;
      description?: string;
    };

interface MintQuoteDocumentBase {
  type: 'mint';
  method: 'bolt11' | 'bolt12' | 'onchain';
  mintUrl: string;
  quoteId: string;
  request: string;
  unit: string;
  amountPaid: string;
  amountIssued: string;
  expiry: string | null;
  createdAt: string;
  updatedAt: string;
}

/** Safe cocod projection of one canonical Mint Quote. */
export type MintQuoteDocument =
  | (MintQuoteDocumentBase & {
      method: 'bolt11';
      amount: string;
      reusable: false;
      state: 'UNPAID' | 'PAID' | 'ISSUED';
    })
  | (MintQuoteDocumentBase & {
      method: 'bolt12';
      amount?: string;
      reusable: true;
    })
  | (MintQuoteDocumentBase & { method: 'onchain'; reusable: true });

/** Offset-paginated canonical Mint Quotes. */
export interface PendingMintQuotesDocument {
  items: MintQuoteDocument[];
  offset: number;
  limit: number;
}

/** Method-specific Melt Quote creation input with lossless decimal amounts. */
export type CreateMeltQuoteRequest =
  | {
      mintUrl: string;
      method: 'bolt11';
      invoice: string;
      amount?: string;
      unit?: string;
    }
  | {
      mintUrl: string;
      method: 'bolt12';
      offer: string;
      amount?: string;
      unit?: string;
    }
  | {
      mintUrl: string;
      method: 'onchain';
      address: string;
      amount: string;
      unit?: string;
    };

interface MeltQuoteDocumentBase {
  type: 'melt';
  method: 'bolt11' | 'bolt12' | 'onchain';
  mintUrl: string;
  quoteId: string;
  request: string;
  unit: string;
  amount: string;
  state: 'UNPAID' | 'PENDING' | 'PAID';
  expiry: string;
  createdAt: string;
  updatedAt: string;
}

/** Safe cocod projection of one canonical Melt Quote. */
export type MeltQuoteDocument =
  | (MeltQuoteDocumentBase & { method: 'bolt11' | 'bolt12'; feeReserve: string })
  | (MeltQuoteDocumentBase & {
      method: 'onchain';
      feeOptions: Array<{ feeIndex: number; feeReserve: string; estimatedBlocks: number }>;
    });

/** Offset-paginated canonical Melt Quotes. */
export interface PendingMeltQuotesDocument {
  items: MeltQuoteDocument[];
  offset: number;
  limit: number;
}

/** Cashu Send Operation preparation input with a lossless decimal amount. */
export interface CreateSendOperationRequest {
  mintUrl?: string;
  amount: string;
  unit: string;
  forceSwap?: boolean;
}

interface SendOperationDocumentBase {
  id: string;
  type: 'send';
  state:
    | 'init'
    | 'prepared'
    | 'executing'
    | 'pending'
    | 'finalized'
    | 'rolling_back'
    | 'rolled_back';
  mintUrl: string;
  unit: string;
  method: 'default' | 'p2pk';
  requestedAmount: string;
  createdAt: string;
  updatedAt: string;
}

/** Explicit safe projection of one Coco Send Operation. */
export type SendOperationDocument =
  | (SendOperationDocumentBase & { state: 'init' })
  | (SendOperationDocumentBase & {
      state: 'prepared' | 'executing' | 'pending' | 'finalized' | 'rolling_back' | 'rolled_back';
      inputAmount: string;
      fee: string;
      needsSwap: boolean;
    });

/** Offset-paginated safe Send Operations. */
export interface SendOperationsDocument {
  items: SendOperationDocument[];
  offset: number;
  limit: number;
}

/** Sensitive, shareable result of a successfully executed Send Operation. */
export interface SendResultDocument {
  token: string;
}

/** Execute response pairing the safe canonical Operation with its sensitive result. */
export interface ExecuteSendOperationResponseDocument {
  operation: SendOperationDocument;
  result: SendResultDocument;
}

const INTERFACE_VERSION = '1' as const;

interface SchemaNode {
  readonly jsonSchema: Readonly<Record<string, unknown>>;
  parse(value: unknown, path: string): unknown;
}

const rfc3339UtcSchema = stringNode({
  format: 'date-time',
  pattern: '^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$',
});
const daemonStatusNode = objectNode({
  version: stringNode(),
  interfaceVersion: literalNode(INTERFACE_VERSION),
});
const walletStatusNode = objectNode({ configuredAt: rfc3339UtcSchema });
const seedAccessStatusNode = objectNode({
  state: enumNode(['locked', 'available']),
  requiresPassphrase: booleanNode(),
});
const lastFailureNode = nullableNode(
  objectNode({
    code: stringNode(),
    message: stringNode(),
    occurredAt: rfc3339UtcSchema,
  }),
);
const cocoSessionStatusNode = objectNode({
  state: enumNode(['stopped', 'starting', 'running', 'stopping', 'failed']),
  startedAt: nullableNode(rfc3339UtcSchema),
  lastFailure: lastFailureNode,
});
const lifecycleStatusNode = unionNode([
  objectNode({
    daemon: daemonStatusNode,
    wallet: literalNode(null),
    seedAccess: literalNode(null),
    cocoSession: cocoSessionStatusNode,
  }),
  objectNode({
    daemon: daemonStatusNode,
    wallet: walletStatusNode,
    seedAccess: seedAccessStatusNode,
    cocoSession: cocoSessionStatusNode,
  }),
]);
const sensitivePassphraseRequestNode = objectNode(
  { passphrase: stringNode({ sensitive: true }) },
  { optional: ['passphrase'] },
);

/** Runtime schema for a route that accepts no request body. */
export const noBodySchema = namedSchema<null>('NoBody', literalNode(null));

/** Runtime and generated schema for `GET /health`. */
export const healthSchema = namedSchema<HealthDocument>(
  'Health',
  objectNode({
    status: literalNode('ok'),
    interfaceVersion: literalNode(INTERFACE_VERSION),
  }),
);

/** Runtime and generated schema for the common v1 error document. */
export const v1ErrorSchema = namedSchema<V1ErrorDocument>(
  'Error',
  objectNode({
    error: objectNode(
      {
        code: enumNode(V1_ERROR_CODES),
        message: stringNode(),
        retryable: booleanNode(),
        details: objectNode({}, { additionalProperties: true }),
      },
      { optional: ['details'] },
    ),
  }),
);

/** Runtime and generated schema for authenticated lifecycle status. */
export const lifecycleStatusSchema = namedSchema<LifecycleStatusDocument>(
  'LifecycleStatus',
  lifecycleStatusNode,
);

/** Runtime and generated schema for Wallet initialization requests. */
export const initializeWalletRequestSchema = namedSchema<InitializeWalletRequest>(
  'InitializeWalletRequest',
  sensitivePassphraseRequestNode,
);

/** Runtime and generated schema for Wallet Recovery Material retrieval requests. */
export const walletRecoveryMaterialRequestSchema = namedSchema<WalletRecoveryMaterialRequest>(
  'WalletRecoveryMaterialRequest',
  sensitivePassphraseRequestNode,
);

/** Runtime and generated schema for Coco Session start requests. */
export const startSessionRequestSchema = namedSchema<StartSessionRequest>(
  'StartSessionRequest',
  sensitivePassphraseRequestNode,
);

/** Runtime and generated schema for Coco Session stop requests. */
export const stopSessionRequestSchema = namedSchema<StopSessionRequest>(
  'StopSessionRequest',
  objectNode({}),
);

/** Runtime and generated schema for Cocod Process shutdown requests. */
export const processShutdownRequestSchema = namedSchema<ProcessShutdownRequest>(
  'ProcessShutdownRequest',
  objectNode({}),
);

/** Runtime and generated schema for the sensitive Wallet initialization response. */
export const initializeWalletResponseSchema = namedSchema<InitializeWalletResponseDocument>(
  'InitializeWalletResponse',
  objectNode({
    generatedMnemonic: stringNode({ sensitive: true }),
    status: lifecycleStatusNode,
  }),
);

/** Runtime and generated schema for sensitive Wallet Recovery Material responses. */
export const walletRecoveryMaterialResponseSchema =
  namedSchema<WalletRecoveryMaterialResponseDocument>(
    'WalletRecoveryMaterialResponse',
    objectNode({ mnemonic: stringNode({ sensitive: true }) }),
  );

/** Runtime and generated schema for accepted Cocod Process shutdown. */
export const processShutdownResponseSchema = namedSchema<ProcessShutdownResponseDocument>(
  'ProcessShutdownResponse',
  objectNode({ status: literalNode('stopping') }),
);

const decimalAmountNode = stringNode({ pattern: '^(0|[1-9]\\d*)$' });

/** Runtime and generated schema for safe Wallet balances. */
export const balancesSchema = namedSchema<BalancesDocument>(
  'Balances',
  objectNode({
    items: arrayNode(
      objectNode({
        mintUrl: stringNode(),
        unit: stringNode(),
        spendable: decimalAmountNode,
        reserved: decimalAmountNode,
        total: decimalAmountNode,
      }),
    ),
  }),
);

const knownMintNode = objectNode({
  mintUrl: stringNode(),
  name: stringNode(),
  trusted: booleanNode(),
  createdAt: rfc3339UtcSchema,
  updatedAt: rfc3339UtcSchema,
});

/** Runtime and generated schema for a request identifying a Mint by URL. */
export const mintUrlRequestSchema = namedSchema<MintUrlRequest>(
  'MintUrlRequest',
  objectNode({ mintUrl: stringNode() }),
);

/** Runtime and generated schema for one safe Known Mint resource. */
export const knownMintSchema = namedSchema<KnownMintDocument>('KnownMint', knownMintNode);

/** Runtime and generated schema for the Known Mint collection. */
export const knownMintsSchema = namedSchema<KnownMintsDocument>(
  'KnownMints',
  objectNode({ items: arrayNode(knownMintNode) }),
);

/** Runtime and generated schema for refreshed Mint metadata. */
export const mintInformationSchema = namedSchema<MintInformationDocument>(
  'MintInformation',
  objectNode({
    mintUrl: stringNode(),
    info: objectNode({}, { additionalProperties: true }),
  }),
);

const paymentMethodCapabilityNode = objectNode(
  {
    operation: enumNode(['mint', 'melt']),
    nut: unionNode([literalNode(4), literalNode(5)]),
    method: stringNode(),
    unit: stringNode(),
    minAmount: nullableNode(decimalAmountNode),
    maxAmount: nullableNode(decimalAmountNode),
    options: anyNode(),
  },
  { optional: ['minAmount', 'maxAmount', 'options'] },
);

/** Runtime and generated schema for Mint and Melt payment-method capabilities. */
export const paymentMethodCapabilitiesSchema = namedSchema<PaymentMethodCapabilitiesDocument>(
  'PaymentMethodCapabilities',
  objectNode({ items: arrayNode(paymentMethodCapabilityNode) }),
);

/** Runtime and generated schema for method-specific Mint Quote creation. */
export const createMintQuoteRequestSchema = namedSchema<CreateMintQuoteRequest>(
  'CreateMintQuoteRequest',
  quoteMethodUnionNode('mint', [
    objectNode(
      {
        mintUrl: stringNode(),
        method: literalNode('bolt11'),
        amount: decimalAmountNode,
        unit: stringNode(),
        locked: booleanNode(),
      },
      { optional: ['locked'] },
    ),
    objectNode({
      mintUrl: stringNode(),
      method: literalNode('onchain'),
      unit: stringNode(),
    }),
    objectNode(
      {
        mintUrl: stringNode(),
        method: literalNode('bolt12'),
        unit: stringNode(),
        amount: decimalAmountNode,
        description: stringNode(),
      },
      { optional: ['amount', 'description'] },
    ),
  ]),
);

const mintQuoteBaseFields = {
  type: literalNode('mint'),
  mintUrl: stringNode(),
  quoteId: stringNode(),
  request: stringNode(),
  unit: stringNode(),
  amountPaid: decimalAmountNode,
  amountIssued: decimalAmountNode,
  expiry: nullableNode(rfc3339UtcSchema),
  createdAt: rfc3339UtcSchema,
  updatedAt: rfc3339UtcSchema,
};

const mintQuoteNode = unionNode([
  objectNode({
    ...mintQuoteBaseFields,
    method: literalNode('bolt11'),
    amount: decimalAmountNode,
    reusable: literalNode(false),
    state: enumNode(['UNPAID', 'PAID', 'ISSUED']),
  }),
  objectNode(
    {
      ...mintQuoteBaseFields,
      method: literalNode('bolt12'),
      amount: decimalAmountNode,
      reusable: literalNode(true),
    },
    { optional: ['amount'] },
  ),
  objectNode({
    ...mintQuoteBaseFields,
    method: literalNode('onchain'),
    reusable: literalNode(true),
  }),
]);

/** Runtime and generated schema for one safe canonical Mint Quote. */
export const mintQuoteSchema = namedSchema<MintQuoteDocument>('MintQuote', mintQuoteNode);

/** Runtime and generated schema for pending canonical Mint Quotes. */
export const pendingMintQuotesSchema = namedSchema<PendingMintQuotesDocument>(
  'PendingMintQuotes',
  objectNode({
    items: arrayNode(mintQuoteNode),
    offset: integerNode({ minimum: 0 }),
    limit: integerNode({ minimum: 1 }),
  }),
);

/** Runtime and generated schema for method-specific Melt Quote creation. */
export const createMeltQuoteRequestSchema = namedSchema<CreateMeltQuoteRequest>(
  'CreateMeltQuoteRequest',
  quoteMethodUnionNode('melt', [
    objectNode(
      {
        mintUrl: stringNode(),
        method: literalNode('bolt11'),
        invoice: stringNode(),
        amount: decimalAmountNode,
        unit: stringNode(),
      },
      { optional: ['amount', 'unit'] },
    ),
    objectNode(
      {
        mintUrl: stringNode(),
        method: literalNode('bolt12'),
        offer: stringNode(),
        amount: decimalAmountNode,
        unit: stringNode(),
      },
      { optional: ['amount', 'unit'] },
    ),
    objectNode(
      {
        mintUrl: stringNode(),
        method: literalNode('onchain'),
        address: stringNode(),
        amount: decimalAmountNode,
        unit: stringNode(),
      },
      { optional: ['unit'] },
    ),
  ]),
);

const meltQuoteBaseFields = {
  type: literalNode('melt'),
  mintUrl: stringNode(),
  quoteId: stringNode(),
  request: stringNode(),
  unit: stringNode(),
  amount: decimalAmountNode,
  state: enumNode(['UNPAID', 'PENDING', 'PAID']),
  expiry: rfc3339UtcSchema,
  createdAt: rfc3339UtcSchema,
  updatedAt: rfc3339UtcSchema,
};

const boltMeltQuoteFields = {
  ...meltQuoteBaseFields,
  feeReserve: decimalAmountNode,
};

const meltQuoteNode = unionNode([
  objectNode({ ...boltMeltQuoteFields, method: literalNode('bolt11') }),
  objectNode({ ...boltMeltQuoteFields, method: literalNode('bolt12') }),
  objectNode({
    ...meltQuoteBaseFields,
    method: literalNode('onchain'),
    feeOptions: arrayNode(
      objectNode({
        feeIndex: integerNode({ minimum: 0 }),
        feeReserve: decimalAmountNode,
        estimatedBlocks: integerNode({ minimum: 0 }),
      }),
    ),
  }),
]);

/** Runtime and generated schema for one safe canonical Melt Quote. */
export const meltQuoteSchema = namedSchema<MeltQuoteDocument>('MeltQuote', meltQuoteNode);

/** Runtime and generated schema for pending canonical Melt Quotes. */
export const pendingMeltQuotesSchema = namedSchema<PendingMeltQuotesDocument>(
  'PendingMeltQuotes',
  objectNode({
    items: arrayNode(meltQuoteNode),
    offset: integerNode({ minimum: 0 }),
    limit: integerNode({ minimum: 1 }),
  }),
);

/** Runtime and generated schema for Cashu Send Operation preparation. */
export const createSendOperationRequestSchema = namedSchema<CreateSendOperationRequest>(
  'CreateSendOperationRequest',
  objectNode(
    {
      mintUrl: stringNode(),
      amount: decimalAmountNode,
      unit: stringNode({ pattern: '\\S' }),
      forceSwap: booleanNode(),
    },
    { optional: ['mintUrl', 'forceSwap'] },
  ),
);

const sendOperationBaseFields = {
  id: stringNode(),
  type: literalNode('send'),
  mintUrl: stringNode(),
  unit: stringNode(),
  method: enumNode(['default', 'p2pk']),
  requestedAmount: decimalAmountNode,
  createdAt: rfc3339UtcSchema,
  updatedAt: rfc3339UtcSchema,
};

const sendOperationNode = unionNode([
  objectNode({ ...sendOperationBaseFields, state: literalNode('init') }),
  objectNode({
    ...sendOperationBaseFields,
    state: enumNode([
      'prepared',
      'executing',
      'pending',
      'finalized',
      'rolling_back',
      'rolled_back',
    ]),
    inputAmount: decimalAmountNode,
    fee: decimalAmountNode,
    needsSwap: booleanNode(),
  }),
]);

/** Runtime and generated schema for one safe Send Operation. */
export const sendOperationSchema = namedSchema<SendOperationDocument>(
  'SendOperation',
  sendOperationNode,
);

/** Runtime and generated schema for paginated safe Send Operations. */
export const sendOperationsSchema = namedSchema<SendOperationsDocument>(
  'SendOperations',
  objectNode({
    items: arrayNode(sendOperationNode),
    offset: integerNode({ minimum: 0 }),
    limit: integerNode({ minimum: 1 }),
  }),
);

const sendResultNode = objectNode({ token: stringNode({ sensitive: true }) });

/** Runtime and generated schema for a sensitive Send Operation result. */
export const sendResultSchema = namedSchema<SendResultDocument>('SendResult', sendResultNode);

/** Runtime and generated schema for Send Operation execution with its result. */
export const executeSendOperationResponseSchema = namedSchema<ExecuteSendOperationResponseDocument>(
  'ExecuteSendOperationResponse',
  objectNode({ operation: sendOperationNode, result: sendResultNode }),
);

/** Maps runtime-owned lifecycle state to its safe v1 representation. */
export function toLifecycleStatusDocument(
  status: CocodStatus,
  daemonVersion: string,
): LifecycleStatusDocument {
  return {
    daemon: { version: daemonVersion, interfaceVersion: INTERFACE_VERSION },
    wallet: status.wallet ? { configuredAt: status.wallet.configuredAt } : null,
    seedAccess: status.seedAccess,
    cocoSession: status.cocoSession,
  };
}

function namedSchema<T>(name: string, node: SchemaNode): RuntimeSchema<T> {
  return {
    name,
    jsonSchema: node.jsonSchema,
    parse(value) {
      return node.parse(value, '$') as T;
    },
  };
}

function literalNode<T extends string | number | boolean | null>(expected: T): SchemaNode {
  return {
    jsonSchema: expected === null ? { type: 'null' } : { const: expected },
    parse(value, path) {
      if (value !== expected) {
        throw new Error(`${path} must equal ${JSON.stringify(expected)}`);
      }
      return expected;
    },
  };
}

function anyNode(): SchemaNode {
  return {
    jsonSchema: {},
    parse(value) {
      return value;
    },
  };
}

function stringNode(
  options: { format?: 'date-time'; pattern?: string; sensitive?: boolean } = {},
): SchemaNode {
  return {
    jsonSchema: {
      type: 'string',
      ...(options.format ? { format: options.format } : {}),
      ...(options.pattern ? { pattern: options.pattern } : {}),
      ...(options.sensitive ? { 'x-sensitive': true } : {}),
    },
    parse(value, path) {
      if (typeof value !== 'string') {
        throw new Error(`${path} must be a string`);
      }
      if (options.pattern && !new RegExp(options.pattern).test(value)) {
        throw new Error(`${path} does not match the required pattern`);
      }
      if (
        options.format === 'date-time' &&
        (!Number.isFinite(Date.parse(value)) || new Date(value).toISOString() !== value)
      ) {
        throw new Error(`${path} must be an RFC 3339 UTC timestamp`);
      }
      return value;
    },
  };
}

function booleanNode(): SchemaNode {
  return {
    jsonSchema: { type: 'boolean' },
    parse(value, path) {
      if (typeof value !== 'boolean') {
        throw new Error(`${path} must be a boolean`);
      }
      return value;
    },
  };
}

function integerNode(options: { minimum?: number; maximum?: number } = {}): SchemaNode {
  return {
    jsonSchema: {
      type: 'integer',
      ...(options.minimum !== undefined ? { minimum: options.minimum } : {}),
      ...(options.maximum !== undefined ? { maximum: options.maximum } : {}),
    },
    parse(value, path) {
      if (
        typeof value !== 'number' ||
        !Number.isSafeInteger(value) ||
        (options.minimum !== undefined && value < options.minimum) ||
        (options.maximum !== undefined && value > options.maximum)
      ) {
        throw new Error(`${path} must be an integer in the allowed range`);
      }
      return value;
    },
  };
}

function arrayNode(item: SchemaNode): SchemaNode {
  return {
    jsonSchema: { type: 'array', items: item.jsonSchema },
    parse(value, path) {
      if (!Array.isArray(value)) {
        throw new Error(`${path} must be an array`);
      }
      return value.map((entry, index) => item.parse(entry, `${path}[${index}]`));
    },
  };
}

function enumNode<const T extends readonly string[]>(values: T): SchemaNode {
  return {
    jsonSchema: { enum: values },
    parse(value, path) {
      if (typeof value !== 'string' || !values.includes(value)) {
        throw new Error(`${path} must be one of ${values.join(', ')}`);
      }
      return value;
    },
  };
}

function quoteMethodUnionNode(type: 'mint' | 'melt', nodes: readonly SchemaNode[]): SchemaNode {
  const supportedMethods = ['bolt11', 'bolt12', 'onchain'];
  const supportedUnion = unionNode(nodes);
  return {
    jsonSchema: supportedUnion.jsonSchema,
    parse(value, path) {
      const record = requireRecord(value, path);
      const method = record.method;
      if (typeof method === 'string' && !supportedMethods.includes(method)) {
        throw new V1HttpError({
          status: 409,
          code: 'unsupported_behavior',
          message: `The ${type === 'mint' ? 'Mint' : 'Melt'} Quote method is unsupported`,
          retryable: false,
          details: { type, method },
        });
      }
      return supportedUnion.parse(value, path);
    },
  };
}

function nullableNode(node: SchemaNode): SchemaNode {
  return unionNode([literalNode(null), node], 'anyOf');
}

function objectNode(
  properties: Readonly<Record<string, SchemaNode>>,
  options: { optional?: readonly string[]; additionalProperties?: boolean } = {},
): SchemaNode {
  const optional = new Set(options.optional ?? []);
  const additionalProperties = options.additionalProperties ?? false;
  const required = Object.keys(properties).filter((key) => !optional.has(key));
  return {
    jsonSchema: {
      type: 'object',
      additionalProperties,
      required,
      properties: Object.fromEntries(
        Object.entries(properties).map(([key, node]) => [key, node.jsonSchema]),
      ),
    },
    parse(value, path) {
      const record = requireRecord(value, path);
      if (!additionalProperties) {
        requireOnlyKeys(record, Object.keys(properties), path);
      }
      const parsed: Record<string, unknown> = additionalProperties ? { ...record } : {};
      for (const [key, node] of Object.entries(properties)) {
        if (!(key in record)) {
          if (optional.has(key)) {
            continue;
          }
          throw new Error(`${path}.${key} is required`);
        }
        parsed[key] = node.parse(record[key], `${path}.${key}`);
      }
      return parsed;
    },
  };
}

function unionNode(nodes: readonly SchemaNode[], keyword: 'oneOf' | 'anyOf' = 'oneOf'): SchemaNode {
  return {
    jsonSchema: { [keyword]: nodes.map((node) => node.jsonSchema) },
    parse(value, path) {
      const matches: unknown[] = [];
      const errors: unknown[] = [];
      for (const node of nodes) {
        try {
          matches.push(node.parse(value, path));
        } catch (error) {
          if (error instanceof V1HttpError) throw error;
          errors.push(error);
        }
      }
      if (matches.length === 0 || (keyword === 'oneOf' && matches.length !== 1)) {
        throw new AggregateError(errors, `${path} does not match ${keyword}`);
      }
      return matches[0];
    },
  };
}

function requireRecord(value: unknown, label: string): Record<string, unknown> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error(`${label} must be an object`);
  }
  return value as Record<string, unknown>;
}

function requireOnlyKeys(
  value: Record<string, unknown>,
  allowedKeys: readonly string[],
  label: string,
): void {
  const allowed = new Set(allowedKeys);
  if (Object.keys(value).some((key) => !allowed.has(key))) {
    throw new Error(`${label} contains an unexpected field`);
  }
}
