import { expect, test } from 'bun:test';

import {
  balancesSchema,
  createMintOperationRequestSchema,
  createMeltOperationRequestSchema,
  createReceiveOperationRequestSchema,
  createMeltQuoteRequestSchema,
  createMintQuoteRequestSchema,
  createSendOperationRequestSchema,
  createV1RouteMetadata,
  evaluatePaymentRequestRequestSchema,
  healthSchema,
  historyPageSchema,
  historySchema,
  initializeWalletRequestSchema,
  initializeWalletResponseSchema,
  executeMeltOperationResponseSchema,
  executeSendOperationResponseSchema,
  knownMintSchema,
  knownMintsSchema,
  lifecycleStatusSchema,
  meltQuoteSchema,
  mintInformationSchema,
  mintOperationSchema,
  mintOperationsSchema,
  meltOperationSchema,
  meltOperationsSchema,
  meltResultSchema,
  mintQuoteSchema,
  mintUrlRequestSchema,
  noSuccessResponseSchema,
  paymentMethodCapabilitiesSchema,
  paymentRequestEvaluationSchema,
  pendingMeltQuotesSchema,
  pendingMintQuotesSchema,
  processShutdownRequestSchema,
  processShutdownResponseSchema,
  receiveOperationSchema,
  receiveOperationsSchema,
  resourceInvalidationEventSchema,
  sendOperationSchema,
  sendOperationsSchema,
  sendResultSchema,
  startSessionRequestSchema,
  stopSessionRequestSchema,
  v1ErrorSchema,
  walletRecoveryMaterialRequestSchema,
  walletRecoveryMaterialResponseSchema,
} from '../../src/v1/http.js';
import { generateV1InterfaceDescription } from '../../src/v1/interface-description.js';

test('the generated v1 interface description comes from the runtime schemas', async () => {
  const generated = generateV1InterfaceDescription(createV1RouteMetadata(), '0.0.17');
  const checkedIn = JSON.parse(
    await Bun.file(new URL('../../docs/lifecycle-api-v1.json', import.meta.url)).text(),
  ) as unknown;

  expect(checkedIn).toEqual(generated);
  expect(generated.schemas).toEqual({
    Error: v1ErrorSchema.jsonSchema,
    Health: healthSchema.jsonSchema,
    LifecycleStatus: lifecycleStatusSchema.jsonSchema,
    EvaluatePaymentRequestRequest: evaluatePaymentRequestRequestSchema.jsonSchema,
    PaymentRequestEvaluation: paymentRequestEvaluationSchema.jsonSchema,
    Balances: balancesSchema.jsonSchema,
    History: historySchema.jsonSchema,
    HistoryPage: historyPageSchema.jsonSchema,
    ResourceInvalidationEvent: resourceInvalidationEventSchema.jsonSchema,
    KnownMints: knownMintsSchema.jsonSchema,
    KnownMint: knownMintSchema.jsonSchema,
    MintUrlRequest: mintUrlRequestSchema.jsonSchema,
    MintInformation: mintInformationSchema.jsonSchema,
    PaymentMethodCapabilities: paymentMethodCapabilitiesSchema.jsonSchema,
    CreateMintQuoteRequest: createMintQuoteRequestSchema.jsonSchema,
    MintQuote: mintQuoteSchema.jsonSchema,
    PendingMintQuotes: pendingMintQuotesSchema.jsonSchema,
    CreateMeltQuoteRequest: createMeltQuoteRequestSchema.jsonSchema,
    MeltQuote: meltQuoteSchema.jsonSchema,
    PendingMeltQuotes: pendingMeltQuotesSchema.jsonSchema,
    CreateMintOperationRequest: createMintOperationRequestSchema.jsonSchema,
    MintOperation: mintOperationSchema.jsonSchema,
    MintOperations: mintOperationsSchema.jsonSchema,
    CreateMeltOperationRequest: createMeltOperationRequestSchema.jsonSchema,
    MeltOperation: meltOperationSchema.jsonSchema,
    MeltOperations: meltOperationsSchema.jsonSchema,
    ExecuteMeltOperationResponse: executeMeltOperationResponseSchema.jsonSchema,
    MeltResult: meltResultSchema.jsonSchema,
    CreateSendOperationRequest: createSendOperationRequestSchema.jsonSchema,
    SendOperation: sendOperationSchema.jsonSchema,
    SendOperations: sendOperationsSchema.jsonSchema,
    ExecuteSendOperationResponse: executeSendOperationResponseSchema.jsonSchema,
    SendResult: sendResultSchema.jsonSchema,
    CreateReceiveOperationRequest: createReceiveOperationRequestSchema.jsonSchema,
    ReceiveOperation: receiveOperationSchema.jsonSchema,
    ReceiveOperations: receiveOperationsSchema.jsonSchema,
    Never: noSuccessResponseSchema.jsonSchema,
    InitializeWalletRequest: initializeWalletRequestSchema.jsonSchema,
    InitializeWalletResponse: initializeWalletResponseSchema.jsonSchema,
    WalletRecoveryMaterialRequest: walletRecoveryMaterialRequestSchema.jsonSchema,
    WalletRecoveryMaterialResponse: walletRecoveryMaterialResponseSchema.jsonSchema,
    StartSessionRequest: startSessionRequestSchema.jsonSchema,
    StopSessionRequest: stopSessionRequestSchema.jsonSchema,
    ProcessShutdownRequest: processShutdownRequestSchema.jsonSchema,
    ProcessShutdownResponse: processShutdownResponseSchema.jsonSchema,
  });
  expect(generated.routes).toEqual([
    {
      method: 'GET',
      path: '/health',
      capability: null,
      requestSchema: null,
      responseSchema: 'Health',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/status',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'LifecycleStatus',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/payment-requests/evaluate',
      capability: 'wallet:read',
      requestSchema: 'EvaluatePaymentRequestRequest',
      responseSchema: 'PaymentRequestEvaluation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/balances',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'Balances',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/history',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'HistoryPage',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/history/{historyEntryId}',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'History',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/events',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'ResourceInvalidationEvent',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: 'no-store',
      responseMediaType: 'text/event-stream',
    },
    {
      method: 'GET',
      path: '/v1/mints',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'KnownMints',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/mints',
      capability: 'wallet:admin',
      requestSchema: 'MintUrlRequest',
      responseSchema: 'KnownMint',
      errorSchema: 'Error',
      successStatuses: [200, 201],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/mints/trust',
      capability: 'wallet:admin',
      requestSchema: 'MintUrlRequest',
      responseSchema: 'KnownMint',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/mints/untrust',
      capability: 'wallet:admin',
      requestSchema: 'MintUrlRequest',
      responseSchema: 'KnownMint',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/mints/info',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'MintInformation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/mints/payment-method-capabilities',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'PaymentMethodCapabilities',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/quotes/mint',
      capability: 'wallet:admin',
      requestSchema: 'CreateMintQuoteRequest',
      responseSchema: 'MintQuote',
      errorSchema: 'Error',
      successStatuses: [201],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/quotes/mint/pending',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'PendingMintQuotes',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/quotes/mint/{quoteId}',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'MintQuote',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/quotes/mint/{quoteId}/refresh',
      capability: 'wallet:admin',
      requestSchema: null,
      responseSchema: 'MintQuote',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/quotes/melt',
      capability: 'wallet:admin',
      requestSchema: 'CreateMeltQuoteRequest',
      responseSchema: 'MeltQuote',
      errorSchema: 'Error',
      successStatuses: [201],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/quotes/melt/pending',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'PendingMeltQuotes',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/quotes/melt/{quoteId}',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'MeltQuote',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/quotes/melt/{quoteId}/refresh',
      capability: 'wallet:admin',
      requestSchema: null,
      responseSchema: 'MeltQuote',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/operations/mint',
      capability: 'wallet:admin',
      requestSchema: 'CreateMintOperationRequest',
      responseSchema: 'MintOperation',
      errorSchema: 'Error',
      successStatuses: [201],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/operations/mint/pending',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'MintOperations',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/operations/mint/in-flight',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'MintOperations',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/operations/mint/{operationId}',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'MintOperation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/operations/mint/{operationId}/execute',
      capability: 'wallet:admin',
      requestSchema: null,
      responseSchema: 'MintOperation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/operations/mint/{operationId}/result',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'Never',
      errorSchema: 'Error',
      successStatuses: [],
      idempotencyKey: null,
      responseCacheControl: 'no-store',
    },
    {
      method: 'POST',
      path: '/v1/operations/mint/{operationId}/refresh',
      capability: 'wallet:admin',
      requestSchema: null,
      responseSchema: 'MintOperation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/operations/melt',
      capability: 'wallet:admin',
      requestSchema: 'CreateMeltOperationRequest',
      responseSchema: 'MeltOperation',
      errorSchema: 'Error',
      successStatuses: [201],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/operations/melt/prepared',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'MeltOperations',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/operations/melt/in-flight',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'MeltOperations',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/operations/melt/{operationId}',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'MeltOperation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/operations/melt/{operationId}/execute',
      capability: 'wallet:admin',
      requestSchema: null,
      responseSchema: 'ExecuteMeltOperationResponse',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: 'no-store',
    },
    {
      method: 'GET',
      path: '/v1/operations/melt/{operationId}/result',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'MeltResult',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: 'no-store',
    },
    {
      method: 'POST',
      path: '/v1/operations/melt/{operationId}/cancel',
      capability: 'wallet:admin',
      requestSchema: null,
      responseSchema: 'MeltOperation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/operations/melt/{operationId}/refresh',
      capability: 'wallet:admin',
      requestSchema: null,
      responseSchema: 'MeltOperation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/operations/melt/{operationId}/reclaim',
      capability: 'wallet:admin',
      requestSchema: null,
      responseSchema: 'MeltOperation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/operations/send',
      capability: 'wallet:admin',
      requestSchema: 'CreateSendOperationRequest',
      responseSchema: 'SendOperation',
      errorSchema: 'Error',
      successStatuses: [201],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/operations/send/prepared',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'SendOperations',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/operations/send/in-flight',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'SendOperations',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/operations/send/{operationId}',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'SendOperation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/operations/send/{operationId}/execute',
      capability: 'wallet:admin',
      requestSchema: null,
      responseSchema: 'ExecuteSendOperationResponse',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: 'no-store',
    },
    {
      method: 'GET',
      path: '/v1/operations/send/{operationId}/result',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'SendResult',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: 'no-store',
    },
    {
      method: 'POST',
      path: '/v1/operations/send/{operationId}/cancel',
      capability: 'wallet:admin',
      requestSchema: null,
      responseSchema: 'SendOperation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/operations/send/{operationId}/refresh',
      capability: 'wallet:admin',
      requestSchema: null,
      responseSchema: 'SendOperation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/operations/send/{operationId}/reclaim',
      capability: 'wallet:admin',
      requestSchema: null,
      responseSchema: 'SendOperation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/operations/receive',
      capability: 'wallet:admin',
      requestSchema: 'CreateReceiveOperationRequest',
      responseSchema: 'ReceiveOperation',
      errorSchema: 'Error',
      successStatuses: [201],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/operations/receive/prepared',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'ReceiveOperations',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/operations/receive/in-flight',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'ReceiveOperations',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/operations/receive/{operationId}',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'ReceiveOperation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/operations/receive/{operationId}/execute',
      capability: 'wallet:admin',
      requestSchema: null,
      responseSchema: 'ReceiveOperation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'GET',
      path: '/v1/operations/receive/{operationId}/result',
      capability: 'wallet:read',
      requestSchema: null,
      responseSchema: 'Never',
      errorSchema: 'Error',
      successStatuses: [],
      idempotencyKey: null,
      responseCacheControl: 'no-store',
    },
    {
      method: 'POST',
      path: '/v1/operations/receive/{operationId}/cancel',
      capability: 'wallet:admin',
      requestSchema: null,
      responseSchema: 'ReceiveOperation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/operations/receive/{operationId}/refresh',
      capability: 'wallet:admin',
      requestSchema: null,
      responseSchema: 'ReceiveOperation',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/admin/wallet/initialize',
      capability: 'wallet:admin',
      requestSchema: 'InitializeWalletRequest',
      responseSchema: 'InitializeWalletResponse',
      errorSchema: 'Error',
      successStatuses: [201, 202],
      idempotencyKey: 'optional',
      responseCacheControl: 'no-store',
    },
    {
      method: 'POST',
      path: '/v1/admin/wallet/recovery-material',
      capability: 'wallet:admin',
      requestSchema: 'WalletRecoveryMaterialRequest',
      responseSchema: 'WalletRecoveryMaterialResponse',
      errorSchema: 'Error',
      successStatuses: [200],
      idempotencyKey: null,
      responseCacheControl: 'no-store',
    },
    {
      method: 'POST',
      path: '/v1/admin/session/start',
      capability: 'wallet:admin',
      requestSchema: 'StartSessionRequest',
      responseSchema: 'LifecycleStatus',
      errorSchema: 'Error',
      successStatuses: [200, 202],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/admin/session/stop',
      capability: 'wallet:admin',
      requestSchema: 'StopSessionRequest',
      responseSchema: 'LifecycleStatus',
      errorSchema: 'Error',
      successStatuses: [200, 202],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
    {
      method: 'POST',
      path: '/v1/admin/process/stop',
      capability: 'wallet:admin',
      requestSchema: 'ProcessShutdownRequest',
      responseSchema: 'ProcessShutdownResponse',
      errorSchema: 'Error',
      successStatuses: [202],
      idempotencyKey: 'optional',
      responseCacheControl: null,
    },
  ]);

  expect(generated.schemas.LifecycleStatus).toHaveProperty('oneOf');
  expect(JSON.stringify(generated.schemas.LifecycleStatus)).toContain(
    '^\\\\d{4}-\\\\d{2}-\\\\d{2}T',
  );
  expect(generated.schemas.WalletRecoveryMaterialRequest).toMatchObject({
    properties: { passphrase: { 'x-sensitive': true } },
  });
  expect(generated.schemas.WalletRecoveryMaterialResponse).toMatchObject({
    properties: { mnemonic: { 'x-sensitive': true } },
  });
  expect(createMintQuoteRequestSchema.jsonSchema.oneOf).toHaveLength(3);
  expect(createMeltQuoteRequestSchema.jsonSchema.oneOf).toHaveLength(3);
  expect(JSON.stringify(createMintQuoteRequestSchema.jsonSchema)).not.toContain('"not"');
  expect(JSON.stringify(createMeltQuoteRequestSchema.jsonSchema)).not.toContain('"not"');

  const cocoSession = { state: 'stopped', startedAt: null, lastFailure: null };
  expect(() =>
    lifecycleStatusSchema.parse({
      daemon: { version: '0.0.17', interfaceVersion: '1' },
      wallet: null,
      seedAccess: { state: 'available', requiresPassphrase: false },
      cocoSession,
    }),
  ).toThrow();
  expect(() =>
    lifecycleStatusSchema.parse({
      daemon: { version: '0.0.17', interfaceVersion: '1' },
      wallet: { configuredAt: '2026-08-16T00:00:00Z' },
      seedAccess: { state: 'available', requiresPassphrase: false },
      cocoSession,
    }),
  ).toThrow();
});
